name: Build

on:
  push:
    paths:
      - version
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Version
        id: version
        run: |-
          echo -n "::set-output name=version::$(cat ./version)"
      - name: Prerelease
        id: prerel
        run: |-
          python -c 'with open("version","r") as f: v=f.read();op=1 if ("alpha" in v) or ("beta" in v) else 0;op="true" if op else "false";print(f"::set-output name=prerel::{op}")'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: ${{ steps.prerel.outputs.prerel }}
